# Generated by Django 4.0.6 on 2023-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Public', 'Public'), ('Member', 'Member'), ('User', 'User')], max_length=10)),
                ('description', models.TextField(max_length=2028)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('org_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(default='Unknown', max_length=255)),
                ('org_name', models.CharField(default='Unknown', max_length=255)),
                ('created_at_position', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
