# Generated by Django 4.0.6 on 2023-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='member_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Member', 'Member'), ('User', 'User')], max_length=10),
        ),
    ]
