# Generated by Django 4.0.6 on 2023-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0003_rename_company_id_announcement_org_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
