# Generated by Django 4.0.6 on 2023-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0004_announcement_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
