# Generated by Django 4.0.6 on 2023-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Announcement', '0005_announcement_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
