# Generated by Django 4.1.6 on 2023-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noftification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('portfolio', models.CharField(max_length=300)),
                ('productName', models.CharField(max_length=300)),
                ('orgName', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=300)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
