# Generated by Django 4.1.6 on 2023-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noftification',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
