# Generated by Django 4.1.6 on 2023-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_noftification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noftification',
            name='companyId',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='noftification',
            name='duration',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
