# Generated by Django 4.1.7 on 2023-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_noftification_companyid_noftification_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noftification',
            name='link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
