# Generated by Django 4.1.6 on 2023-03-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('portfolio', models.CharField(max_length=300)),
                ('productName', models.CharField(max_length=300)),
                ('action', models.BooleanField(max_length=300, null=True)),
                ('orgName', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
