# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='action',
            field=models.BooleanField(max_length=300, null=True),
        ),
    ]
