# Generated by Django 4.1.6 on 2023-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
