# Generated by Django 4.1.6 on 2023-03-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_alter_favourite_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
