# Generated by Django 4.1.7 on 2023-03-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_alter_favourite_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='action',
            field=models.BooleanField(default=True, max_length=300),
        ),
    ]
